### ISSUE TITLE
Loop usage example?

### ISSUE THREAD

**Issue by kkhao** [eclipse-zenoh-flow/zenoh-flow-python#13] opened 2022-04-22 03:39 UTC
I found that zenoh-flow supports _Loop_ feature, but I don't know its specific usage. For example, how can I implement operators loop like  **A->B->C->A**. Could you show me some _Loop_ usage examples？

**Comment by J-Loudet** [comment] 2022-04-26 15:22
Hi @kkhao!

For now, we do not expose everything to the Python bindings. What this means is you will not have access to some information --- although it will be working under the hood as "intended".

If you still want to use it, below is a description of how it works!

## Declaration

The way it was designed, you need to specify in the YAML file the starting (_ingress_) and ending (_egress_) points of your Loop.

The following is a valid Loop declaration:

```yaml
loops:
- ingress: A
  egress: C
  feedback_port: feedback-AC
  is_infinite: false
  port_type: any
```

When a Zenoh Flow daemon sees this declaration it will first check its "validity". In particular, it will check that:
- there is a path between the ingress and egress,
- node A is not used as an ingress / egress in another Loop,
- node C is not used as an ingress / egress in another Loop,
- node A, resp. node C, does not have an input, resp. output, with that same name,
- node A only has a single output,
- node C only has a single input.

Once these checks pass, it will add a an **input** to the ingress that will have the name provided after `feedback_port`. Similarly, it will create an **output** to the egress with the same name.

The field `is_infinite` dictates the presence of a _counter_ in the `LoopContext` associated to the messages (see below for more information about this context).

The field `port_type` is for coherence with the rest of the declaration of inputs & outputs.

## Loop Context

⚠️ **We do not expose this context in the Python bindings.**

For every message that is inside a Loop, a `LoopContext` is associated. This context gives the following information:
- the ingress,
- the egress,
- the iteration,
- the starting timestamp of the very first iteration,
- the starting timestamp of the current iteration,
- the duration of the previous iteration.

The iteration will keep track of the number of iterations if the loop was declared as being _finite_ (i.e. `is_infinite: false`).
This `LoopContext` is stripped from messages once they exit the Loop.

## Behavior

Once a message arrives at the ingress node of a Loop, we create a context. This context is forwarded with the message and only removed once it exits the Loop at the egress.

To continue a Loop (which has the effect of updating the `LoopContext`), the message should be transmitted on the **feedback port** of the Egress. If a message is sent on the "regular" output of the Egress, it is considered as exiting the Loop. 

## Code usage

To get the feedback in the Ingress:

```python
def run(self, context, state, inputs):
    feedback = inputs.get('feedback-AC')
    # …
```

To continue the Loop, in the Egress:

```python
# Code for node C
def run(self, context, state, inputs):
    # perform computation to produce data
    data = …
    return { 'feedback-AC': data }
```

To stop the Loop (assuming the node C has the "regular" output `foo`):

```python
# Code for node C
def run(self, context, state, inputs):
    # perform computation to produce data
    data = …
    return { 'foo': … }
```

**Comment by kkhao** [comment] 2022-04-27 08:55
Thank you very much for your reply, @J-Loudet .

**Comment by kkhao** [comment] 2022-04-28 03:45
Hi, @J-Loudet !
I ran a sample, but it has problems, and the error was as follows:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidData("Port < endOperatorMsg > already exists for Egress < EndOperator >")', runtime/src/main.rs:79:90
```
I think there might be a conflict between _sink_ and _loop_, but I don't know how to solve it. The YAML file is as follows：
```
flow: TestPipeline
operators:
  - id: HeadOperator
    uri: file://./test/head_operator.py
    inputs:
     - id: testMsg
       type: usize
    outputs:
     - id: headOperatorMsg
       type: usize

  - id: EndOperator
    uri: file://./test/end_operator.py
    inputs:
     - id: headOperatorMsg
       type: usize
    outputs:
     - id: endOperatorMsg
       type: usize

sources:
  - id: testSrc
    uri: file://./sources/test_source.py
    output:
      id: testMsg
      type: usize

sinks:
  - id : testSink
    uri: file://./sinks/test_sink.py
    input:
        id: endOperatorMsg
        type: usize

links:
- from:
    node : testSrc
    output : testMsg
  to:
    node : HeadOperator
    input : testMsg
- from:
    node : HeadOperator
    output : headOperatorMsg
  to:
    node : EndOperator
    input : headOperatorMsg
- from:
    node : EndOperator
    output : endOperatorMsg
  to:
    node : testSink
    input : endOperatorMsg

loops:
- ingress: HeadOperator
  egress: EndOperator
  feedback_port: endOperatorMsg
  port_type: int
  is_infinite: false
```

**Comment by gabrik** [comment] 2022-04-28 06:29
Hi @kkhao you must change the name of the feedback port to something else, otherwise, it will try to add another port named `endOperatorMsg` to `EndOperator` that will conflict with the one defined in the operator section.

**Comment by J-Loudet** [comment] 2022-11-07 09:37
Closing as in the upcoming new API (0.4.0), loops require no specific extra steps.

**Closed as completed by J-Loudet** 2022-11-07 09:37 UTC
